# Generated by Django 3.0.8 on 2020-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=25, unique=True)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
